Fix default value for --skip-prefix
with `default_value = ""` the CLI parser would complain:

    error: a value is required for '--skip-prefix <SKIP_PREFIX>' but none was supplied

which is surprising, since that doesn't happen for `--skip-dir` even
though they were defined near identically, which suggests there must be
something different about how `OsString` and `PathBuf` are parsed.

Nonetheless, it looks simplest to just avoid explicit defaults for such
multi-value options and let Clap assume an empty `Vec`.